# Site settings
title: Maryane Castro blog
email: 
description: "programming and animals."
baseurl: "/blog"
url: "http://maryane-castro.github.io"
github_username:  maryane-castro
linkedin_username: maryane-castro
# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
